### ISSUE TITLE
Is this mod dead?

### ISSUE THREAD

**Issue by kylepitcock** [StonedCoal/OakNet-Link-New#19]
It’s been almost 10 months since the last issue was posted and curseforge page update

**Comment by StonedCoal** [comment]
Well I haven't got much time left for developing that mod. I was not able to achive a stable connection After several netcode rewrites so I kinda lost the motivation. Perhaps sometime I'll continue the development.

**Comment by kylepitcock** [comment]
Damn, this mod had a really cool concept. Perhaps you can find a group of people that are really experienced in mods to pick it up.

**Comment by StonedCoal** [comment]
Hmm I'm currently working on another peer to peer api, perhaps I can use that for this mod. After all I made the current version open source so if someone wants to help they could do. My concept is also really easy to port for newer minecraft versions so that shouldn't be a problem either...

**Comment by StonedCoal** [comment]
Hey, good news it seems as the new API works like it should, tests with Minecraft seemd to be promising, stay tuned for it

**Comment by StonedCoal** [comment]
It seems that there are still people visiting this site so here is a current state of the project.

OakNet-Link will be a more general system allowing to create easy multiplayer servers for all server client based games. even LAN games could be possible. For realising that the programm emulates a network device which is used to create a simple peer to peer VPNs. 
The program will also provide an easy interface to create and manage gameservers.
Connections will be established by simply running the program and typing "name.oaknet.link" in the ingame adress field of the desired game.

Current Progress:
- Virtual network device: working, untested
- Peer to Peer VPNs: working, untested
- UI: In development
- Server management: Not implemented
- DNS system: Not implemented

Screenshot:
![image](https://user-images.githubusercontent.com/6567673/156903741-4fb4a4a7-4937-4122-b55f-a336275c536c.png)

In the near future I'll push the current state to the repo and change the readme.

**Comment by Bennyboiii** [comment]
Hey, I'm really interested in this project, especially since this announcement to move to a more general model. I have heard from so many people that p2p open world games are basically uncharted territory, and I desperately want to prove them wrong lmao. I have two questions about this:

One:I think I understand that, at least for now, you are using a proxy model to connect peers to each other. Do you ever intend to switch to peer tunneling? I'm just worried that if the project ever changes hands or dies, we wouldn't be able to play because the VPN will eventually die (I'm a bit of a game preservationist, and "servers" with longer lifetimes and a higher scalability would be game changing)

Two: Will you eventually release an incomplete version of this mod for curiosity'S sake? It would be neat to look through the source code as it is now. I'm more interested in the mechanics behind it than actually seeing it working (until it's testable ofc).

I don't want to project my own interests onto you too much, so while I do have other ideas I wanna get out there, I think I'll write them up on my own lmao. I'm glad you are continuing this project!

**Comment by StonedCoal** [comment]
Hey hey, thanks for your reply.

The original approach of the system used a pure proxy system which I scraped early because it used up to much server processing power from my side.

The current approach uses direct tunneling to the "host" or rather more the ip destination.
The "VPN" part comes from the usage of an virtual network device to route raw IP packets to other peers. 
You send a packet to a private ip address and the system finds the peer which has this address in the oaknet link network and establishes a direct tunnel connection to said pair. 
I only use a rendezvous server to exchange peer data and keep track of the private ip address to peer association. As well as some DNS stuff so that you can eventually connect to peers using the oaknet.link domain.

I surely can upload the current state after some cleanup, but I don't have much documentation yet. If you like to help or get further information you can add me on discord: Akinito#2341

**Comment by StonedCoal** [comment]
Here we go, current state is pushed ;D

**Comment by deathbird909** [comment]
"I only use a rendezvous server to exchange peer data and keep track of the private ip address to peer association."

Cool project. Made me think: I believe Retroshare uses the Bittorrent Distributed Hash Table as a proxy system for connecting F2F peers. Not the direction you're heading right now maybe, but an interesting idea? https://retroshare.readthedocs.io/en/latest/user-guide/settings/#network
